name: "GAR build/push/sign"
description: "Build, push, and sign (to Google Artifact Registry and optionally to GHCR)"
inputs:
  dockerfile:
    description: "Dockerfile path"
    default: "Dockerfile"
  name:
    description: "Name of image"
    required: true
  google_service_account:
    description: "Name of google service account to impersonate"
    required: true
  push:
    description: "Whether or not to push image"
    default: true
  push_ghcr:
    description: "Whether or not to push image to GHCR"
    default: false
  workload_identity_provider:
    description: "The workload identity provider for google service account impersonation"
    required: true
  registry:
    description: "The Google Artifact Registry path to push image to"
    default: "europe-north1-docker.pkg.dev/nais-io/nais/images"
  build_args:
    description: "List of build args"
    required: false
  build_secrets:
    description: "List of secrets"
    required: false
  sbom:
    description: "existing SBOM in cyclonedx format"
    default: "auto-generate-for-me-please.json"
  extra_tags:
    description: "A list of tags to be applied in addition to the detailed time+sha-tag and latest-tag"
    default: ""
  multi-platform:
    description: "Build multi-platform images, supporting amd64 and arm64"
    default: "false"
  context:
    description: "Docker build context"
    default: "."
outputs:
  tag:
    description: "full image tag"
    value: ${{ steps.outputs.outputs.tag }}
  version:
    description: "version"
    value: ${{ steps.outputs.outputs.version }}
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      if: "${{ inputs.multi-platform == 'true' }}"
      uses: docker/setup-qemu-action@e81a89b1732b9c48d79cd809d8d81d79c4647a18 # ratchet:docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # ratchet:docker/setup-buildx-action@v2
    - id: "auth"
      name: "Authenticate to Google Cloud"
      if: ${{ inputs.push == 'true' }}
      uses: "google-github-actions/auth@35b0e87d162680511bf346c299f71c9c5c379033" # ratchet:google-github-actions/auth@v1.1.1
      with:
        workload_identity_provider: "${{ inputs.workload_identity_provider }}"
        service_account: "${{ inputs.google_service_account }}@nais-io.iam.gserviceaccount.com"
        token_format: "access_token"
    - name: "Login to registry"
      if: ${{ inputs.push == 'true' }}
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # ratchet:docker/login-action@v2
      with:
        registry: "${{ inputs.registry }}"
        username: "oauth2accesstoken"
        password: "${{ steps.auth.outputs.access_token }}"
    - name: "Login to GitHub Container Registry"
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # ratchet:docker/login-action@v2
      if: ${{ inputs.push_ghcr == 'true' }}
      with:
        registry: "ghcr.io"
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    - name: "Docker metadata"
      id: "metadata"
      uses: docker/metadata-action@c4ee3adeed93b1fa6a762f209fb01608c1a22f1e # ratchet:docker/metadata-action@v4
      with:
        images: |
          "${{ inputs.registry }}/${{ inputs.name }}"
          name=ghcr.io/${{ github.repository_owner }}/${{ inputs.name }},enable=${{ inputs.push_ghcr == 'true' }}
        tags: |
          type=raw,value={{date 'YYYY.MM.DD-HH.mm.ss' tz='Europe/Oslo'}}-{{sha}}
          type=raw,value=latest
          type=raw,value=${{inputs.extra_tags}}
    - name: "Select platforms"
      id: multi-platform
      shell: bash
      run: |
        if [[ "${{ inputs.multi-platform }}" == 'true' ]]; then
          echo "platforms=linux/amd64,linux/arm64" >> $GITHUB_OUTPUT
        else
          echo "platforms=linux/amd64" >> $GITHUB_OUTPUT
        fi
    - name: "Build and push"
      id: "build_push"
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671 # ratchet:docker/build-push-action@v4
      with:
        context: "${{ inputs.context }}"
        platforms: "${{ steps.multi-platform.outputs.platforms }}"
        file: "${{ inputs.dockerfile }}"
        push: ${{ inputs.push }}
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        build-args: ${{ inputs.build_args }}
        secrets: ${{ inputs.build_secrets }}
    - name: Write summary
      shell: bash
      run: |
        echo '### tags' >> $GITHUB_STEP_SUMMARY
        echo '${{ steps.metadata.outputs.tags }}' >> $GITHUB_STEP_SUMMARY
    - name: "Generate SBOM, attest and sign image"
      if: ${{ inputs.push == 'true' }}
      uses: nais/attest-sign@v1.1.0
      with:
        image_ref: ${{ inputs.registry }}/${{ inputs.name }}@${{ steps.build_push.outputs.digest }}
        sbom: ${{ inputs.sbom }}
    - name: "Generate SBOM, attest and sign image (GHCR)"
      if: ${{ inputs.push_ghcr == 'true' }}
      uses: nais/attest-sign@v1.1.0
      with:
        image_ref: ghcr.io/${{ github.repository_owner }}/${{ inputs.name }}@${{ steps.build_push.outputs.digest }}
        sbom: ${{ inputs.sbom }}
    - name: "Set outputs"
      id: outputs
      shell: bash
      run: |
        echo "tag=${{ fromJSON(steps.metadata.outputs.json).tags[0] }}" >> $GITHUB_OUTPUT
        echo "version=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.version'] }}" >> $GITHUB_OUTPUT
