name: "GAR build/push/sign"
description: "Build, push, and sign (to Google Artifact Registry)"
inputs:
  dockerfile:
    description: "Dockerfile path"
    default: "Dockerfile"

  name:
    description: "Name of image"
    required: true

  google_service_account:
    description: "Name of google service account to impersonate"
    required: true

  push:
    description: "Whether or not to push and sign image"
    default: true
    type: boolean

  workload_identity_provider:
    description: "The workload identity provider for google service account impersonation"
    required: true

  registry:
    description: "The Google Artifact Registry path to push image to"
    default: "europe-north1-docker.pkg.dev/nais-io/nais/images"

  build_args:
    description: "List of build args"
    required: false

  sbom:
    description: 'existing SBOM in cyclonedx format'
    default: 'auto-generate-for-me-please.json'

  extra_tags:
    description: 'A list of tags to be applied in addtion to the detailed time+sha-tag and latest-tag'
    default: ''

outputs:
  tag:
    description: "full image tag"
    value: ${{ steps.outputs.outputs.tag }}
  version:
    description: "version"
    value: ${{ steps.outputs.outputs.version }}

runs:
  using: "composite"
  steps:
    - id: "auth"
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@ef5d53e30bbcd8d0836f4288f5e50ff3e086997d" # ratchet:google-github-actions/auth@v1.0.0
      with:
        workload_identity_provider: "${{ inputs.workload_identity_provider }}"
        service_account: "${{ inputs.google_service_account }}@nais-io.iam.gserviceaccount.com"
        token_format: "access_token"

    - name: "Login to registry"
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a # ratchet:docker/login-action@v2
      with:
        registry: "${{ inputs.registry }}"
        username: "oauth2accesstoken"
        password: "${{ steps.auth.outputs.access_token }}"

    - name: "Docker metadata"
      id: "metadata"
      uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96 # ratchet:docker/metadata-action@v4
      with:
        images: "${{ inputs.registry }}/${{ inputs.name }}"
        tags: |
          type=raw,value={{date 'YYYYMMDD-hhmmss' tz='Europe/Oslo'}}-{{sha}}
          type=raw,value=latest
          type=raw,value=${{inputs.extra_tags}}
    - name: "Build and push"
      id: "build_push"
      uses: docker/build-push-action@1104d471370f9806843c095c1db02b5a90c5f8b6 # ratchet:docker/build-push-action@v3
      with:
        context: .
        file: "${{ inputs.dockerfile }}"
        push: ${{ inputs.push }}
        tags: ${{ steps.metadata.outputs.tags }}
        labels: ${{ steps.metadata.outputs.labels }}
        build-args: ${{ inputs.build_args }}

    - name: "Generate SBOM, attest and sign image"
      uses: nais/attest-sign@v1.0.0
      if: ${{ inputs.push }}
      with:
        image_ref: ${{ inputs.registry }}/${{ inputs.name }}@${{ steps.build_push.outputs.digest }}
        sbom: ${{ inputs.sbom }}

    - name: "Set outputs"
      id: outputs
      shell: bash
      run: |
        echo "tag=${{ fromJSON(steps.metadata.outputs.json).tags[0] }}" >> $GITHUB_OUTPUT
        echo "version=${{ fromJSON(steps.metadata.outputs.json).labels['org.opencontainers.image.version'] }}" >> $GITHUB_OUTPUT
